# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: 
github: https://github.com/chinaran

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
- links

# Links
links: 
  Hexo: http://hexo.io
  快递查询: http://m.kuaidi100.com

# Miscellaneous
# google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

